export const GAME_CONFIG = {
  WORLD_SIZE: 4000,

  PLAYER: {
    BASE_SPEED: 220,
    BASE_HP: 100,
    BASE_DAMAGE: 25,
    BASE_ATTACK_RATE: 0.25,
    BASE_ATTACK_RANGE: 80,
    BASE_SIZE: 22,
    LEVEL_XP_BASE: 100,
    LEVEL_XP_MULTIPLIER: 1.5,
    GEM_PICKUP_RADIUS: 100,
    GEM_ATTRACT_SPEED: 400,
    GEM_COLLECT_DISTANCE: 20,
    DAMAGE_COLLISION_DISTANCE: 20,
  },

  SPAWNING: {
    BASE_SPAWN_RATE: 0.05,
    BASE_MAX_ENEMIES: 50,
    ENEMIES_PER_WAVE: 10,
    SPAWN_DISTANCE_BUFFER: 100,
  },

  WAVE: {
    KILLS_PER_WAVE: 20,
    BOSS_INTERVAL: 5,
  },

  PROJECTILE: {
    BASE_SPEED: 500,
    BASE_LIFE: 2,
    BASE_SIZE: 4,
  },

  ABILITY: {
    VENOM_BURST: { COOLDOWN: 5, RADIUS: 150, DAMAGE: 50 },
    LIGHTNING_STING: { COOLDOWN: 8, RANGE: 300, DAMAGE: 100 },
    CHITIN_SHIELD: { COOLDOWN: 12, HEAL: 50 },
    DEATH_SWARM: { COOLDOWN: 20, RADIUS: 200, DAMAGE: 80 },
  },

  ENEMY: {
    HORNET_RANGE: 200,
    HORNET_COOLDOWN: 2,
  },

  RENDER: {
    GRID_SIZE: 100,
    GEM_SIZE: 4,
    SHADOW_BLUR: 10,
  },

  AUDIO: {
    ATTACK_PITCH: 1.0,
    HIT_PITCH: 0.8,
    KILL_PITCH: 1.2,
  },
} as const;

export const ENEMY_SPAWN_WAVES = {
  WASP_WAVE: 2,
  MOTH_WAVE: 4,
  SOLDIER_WAVE: 6,
  SPITTER_WAVE: 8,
  TANK_WAVE: 10,
} as const;

export const ENEMY_SPAWN_CHANCE = {
  WASP: 0.3,
  MOTH: 0.2,
  SOLDIER: 0.15,
  SPITTER: 0.15,
  TANK: 0.1,
} as const;

export const WAVE_DIFFICULTY = {
  ENEMY_HP_MULT: 0.2,
  BOSS_HP_MULT: 0.5,
} as const;
